### ISSUE TITLE
MongoDB error when an already-noticed rename happens

### ISSUE THREAD

**Issue by PartMan7** [PartMan7/PartBot#5]
```
/home/partman/Documents/Code/PartBotter/node_modules/mongodb/src/cmap/connection.ts:413
        callback(new MongoServerError(document));
                 ^
MongoServerError: E11000 duplicate key error collection: partbotter.alts index: id_1 dup key: { : "partman-fakepart" }
    at Connection.onMessage (/home/partman/Documents/Code/PartBotter/node_modules/mongodb/src/cmap/connection.ts:413:18)
    at MessageStream.<anonymous> (/home/partman/Documents/Code/PartBotter/node_modules/mongodb/src/cmap/connection.ts:243:56)
    at MessageStream.emit (node:events:513:28)
    at MessageStream.emit (node:domain:489:12)
    at processIncomingData (/home/partman/Documents/Code/PartBotter/node_modules/mongodb/src/cmap/message_stream.ts:193:12)
    at MessageStream._write (/home/partman/Documents/Code/PartBotter/node_modules/mongodb/src/cmap/message_stream.ts:74:5)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at MessageStream.Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22) {
  ok: 0,
  code: 11000,
  codeName: 'DuplicateKey',
  [Symbol(errorLabels)]: Set(0) {}
}
```

**Comment by PartMan7** [comment]
Fixed in c5355ac47d09919c2421afda3c5ca13ea7226a5e
